port: 9090
logger-output-path: "path-to-log"

oauthStateString: "random-string"
google:
  clientID: "client-id-google"
  clientSecret: "client-secret-google"
facebook:
  clientID: "client-id-facebook"
  clientSecret: "client-secret-facebook"
